'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IB_TWS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;IBSettings&gt;
        '''  &lt;Connection&gt;
        '''    &lt;IPAddress&gt;127.0.0.1&lt;/IPAddress&gt;
        '''    &lt;Port&gt;5001&lt;/Port&gt;
        '''    &lt;ClientID&gt;0&lt;/ClientID&gt;
        '''    &lt;ServerLogLevel&gt;4&lt;/ServerLogLevel&gt;
        '''  &lt;/Connection&gt;
        '''  &lt;TickerAttributes&gt;
        '''    &lt;StkType&gt;STK&lt;/StkType&gt;
        '''    &lt;Exchange&gt;NSE&lt;/Exchange&gt;
        '''    &lt;PrimExchange&gt;NSE&lt;/PrimExchange&gt;
        '''    &lt;Currency&gt;INR&lt;/Currency&gt;
        '''    &lt;ContractID /&gt;
        '''    &lt;Expiry /&gt;
        '''    &lt;Strike&gt;0&lt;/Strike&gt;
        '''    &lt;Right /&gt;
        '''    &lt;Multiplier /&gt;
        '''    &lt;LocalSymbol /&gt;
        '''    &lt;TradingClass /&gt;
        '''    &lt;IncEx [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ibSet() As String
            Get
                Return ResourceManager.GetString("ibSet", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
